version: 2
updates:
    -   package-ecosystem: gomod
        directory: /web
        schedule:
            interval: monthly
        groups:
            dependencies:
                patterns:
                    - "*"
    -   package-ecosystem: npm
        directory: /cms
        schedule:
            interval: monthly
        groups:
            payload-helper:
                patterns:
                    - "@ainsleydev/payload-helper"
