name: Lint

on:
    workflow_dispatch:
    pull_request:
        branches: [ main ]

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [ 1.22.x ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: ${{ matrix.go-version }}

            - name: Setup Biome
              uses: biomejs/setup-biome@v2
              with:
                  version: latest

            -   name: Lint Go
                uses: golangci/golangci-lint-action@v6
                with:
                    version: latest
                    skip-go-installation: true
                    skip-cache: true
                    args: --verbose
                    timeout: 5m
                    working-directory: web

            -   name: Run Biome
                run: biome ci .

            -   name: Diff
                run: git diff
